language: python
before_install:
  - ./ci/setup-server.sh
script:
  - nosetests -v -s
env:
  - CCNET_CONF_DIR=/tmp/ccnet SEAFILE_CONF_DIR=/tmp/seafile-data
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
notifications:
  email:
    recipients:
      - linshuai2012@gmail.com